### ISSUE TITLE
 Unsupported platform for fsevents@1.1.2

### ISSUE THREAD

**Issue by VESoft** [transistorsoft/background-geolocation-console#32]
Hello, I have had problems deploying to a Background Geolocation Console server, I have executed a npm install command and I have been given an error message npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules / chokidar / node_modules / fsevents):
Npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.2: wanted {"os": "darwin", "arch": "any"} (current: {"os": "linux", "arch": "X64"}).

In other words, fsevents does not run on linux, the command "npm run server" throws me
> Background-geolocation-console@2.0.0 server / home4 / momentoi / public_html / tracker
> Babel-node --presets = 'node6' server.js

Db: undefined
Aborted

The npm command correctly installed all dependencies, except this "fsevents", so I see in the code is used in many calls, is there any way to run the console without needing that package?

Is there a way to configure access to the database manually, ie without running the creation query of the locations table?

I urgently require an option to deploy the server, I am attentive, thanks

**Comment by ZeusTheTrueGod** [comment]
@VESoft first of all, Db: undefined itself is not a problem, although the message is confusing.
The next line in console should be like 
```
Executing (default): SELECT 1+1 AS result
```

**Comment by ZeusTheTrueGod** [comment]
Next, the DATABASE_URL env variable allows you to specify a url path to postgresql or sql database, but when omitted, it will create a database by default.
Finally,  fs events warnings should not cause any issues at all.

**Comment by ZeusTheTrueGod** [comment]
I'd also like to know, are you deploying to your own server or have you have an issue on your local workstation ?

**Comment by ZeusTheTrueGod** [comment]
If you are deploying to your own server, then please review the `server_deploy.bash`. You can change the ip address to your own server ip address, and this way a bash script will install postgres, set everything to the production mode and then deploy. Also, we support a `tracker.transistorsoft.com` instance, it is a shared server for those who have issues with set up of their own servers. In order to use it, please use 'npm start open' from cordova sample app or react native sample app. It is a server deployed via 'server_deploy.bash' script with everything set up for multiple users and production mode
